apiVersion: fission.io/v1
kind: Environment
metadata:
  name: java-env
  namespace: default
  creationTimestamp: null
spec:
  TerminationGracePeriod: 360
  builder: 
    command: build
    image: fission/jvm-builder:0.9.2
  keeparchive: true
  poolsize: 3
  resources: {}
  runtime:
    functionendpointport: 0
    image: ghcr.io/fission/jvm-env
    loadendpointpath: ""
    loadendpointport: 0
  version: 3
